/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2019-02-22 10:59:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBxLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>IDS</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<!--\r\n");
      out.write("Template 2063 Wide Mode\r\n");
      out.write("http://www.tooplate.com/view/2063-wide-mode\r\n");
      out.write("-->\r\n");
      out.write("<link href=\"tooplate_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/JavaScript\" src=\"js/jquery-1.6.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/ddsmoothmenu.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ddsmoothmenu.js\">\r\n");
      out.write("\r\n");
      out.write("/***********************************************\r\n");
      out.write("* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)\r\n");
      out.write("* This notice MUST stay intact for legal use\r\n");
      out.write("* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code\r\n");
      out.write("***********************************************/\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("ddsmoothmenu.init({\r\n");
      out.write("\tmainmenuid: \"tooplate_menu\", //menu DIV id\r\n");
      out.write("\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\r\n");
      out.write("\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\r\n");
      out.write("\t//customtheme: [\"#1c5a80\", \"#18374a\"],\r\n");
      out.write("\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slimbox2.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("<script type=\"text/JavaScript\" src=\"js/slimbox2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nivo-slider.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

   if(request.getParameter("login")!=null)
   {
  	 out.println("<script>alert('login Successfully')</script>");
   }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_header\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.jsp\"><font color=\"white\">Intrusion\r\n");
      out.write("\t\t\t\t\t\t\tDetection System</font></a>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END of header -->\r\n");
      out.write("\t\t<div id=\"tooplate_main_wrapper\">\r\n");
      out.write("\t\t\t<span class=\"tmw_frame tmw_framet\"></span><span\r\n");
      out.write("\t\t\t\tclass=\"tmw_frame tmw_frameb\"></span>\r\n");
      out.write("\t\t\t<div id=\"tooplate_menu\" class=\"ddsmoothmenu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\" class=\"selected\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"upload.jsp\">Upload</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"received.jsp\">Receive</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<br style=\"clear: left\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end of tooplate_menu -->\r\n");
      out.write("\t\t\t<!-- END of slider -->\r\n");
      out.write("\t\t\t<div id=\"tooplate_main\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"content_wrapper content_mb_60\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col_2\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col_2 no_margin_right\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear h30\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"display: none;\" class=\"nav_up\" id=\"nav_up\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END of main wrapper -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END of tooplate_wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_footer_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_footer\">\r\n");
      out.write("\t\t\t<marquee>Intrusion Detection System</marquee>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t<!-- END of tooplate_footer -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END of tooplate_footer_wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_copyright_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_copyright\">\r\n");
      out.write("\t\t\tCopyright Â© 2048 Your Company Name | Design: <a\r\n");
      out.write("\t\t\t\thref=\"http://www.tooplate.com\">Tooplate</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/scroll-startstop.events.jquery.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar $elem = $('#content');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#nav_up').fadeIn('slow');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(window).bind('scrollstart', function(){\r\n");
      out.write("\t\t\t$('#nav_up,#nav_down').stop().animate({'opacity':'0.2'});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(window).bind('scrollstop', function(){\r\n");
      out.write("\t\t\t$('#nav_up,#nav_down').stop().animate({'opacity':'1'});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#nav_up').click(\r\n");
      out.write("\t\t\tfunction (e) {\r\n");
      out.write("\t\t\t\t$('html, body').animate({scrollTop: '0px'}, 800);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
