/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2019-02-22 10:57:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>IDS</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<!--\r\n");
      out.write("Template 2063 Wide Mode\r\n");
      out.write("http://www.tooplate.com/view/2063-wide-mode\r\n");
      out.write("-->\r\n");
      out.write("<link href=\"tooplate_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/JavaScript\" src=\"js/jquery-1.6.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/ddsmoothmenu.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ddsmoothmenu.js\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"jquery.datepick.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"jquery.plugin.js\"></script>\r\n");
      out.write("<script src=\"jquery.datepick.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$('#popupDatepicker').datepick();\r\n");
      out.write("\t$('#inlineDatepicker').datepick({onSelect: showDate});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function showDate(date) {\r\n");
      out.write("\talert('The date chosen is ' + date);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("ddsmoothmenu.init({\r\n");
      out.write("\tmainmenuid: \"tooplate_menu\", //menu DIV id\r\n");
      out.write("\torientation: 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\r\n");
      out.write("\tclassname: 'ddsmoothmenu', //class added to menu's outer DIV\r\n");
      out.write("\t//customtheme: [\"#1c5a80\", \"#18374a\"],\r\n");
      out.write("\tcontentsource: \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slimbox2.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("<script type=\"text/JavaScript\" src=\"js/slimbox2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nivo-slider.css\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function AllowAlphabet() {\r\n");
      out.write("\tif (!userreg.fname.value.match(/^[a-zA-Z]+$/)\r\n");
      out.write("\t&&userreg.fname.value != \"\") {\r\n");
      out.write("\t\tuserreg.fname.value = \"\";\r\n");
      out.write("\t\tuserreg.fname.focus();\r\n");
      out.write("\talert(\"Please Enter only alphabet in text\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t\r\n");
      out.write("\tif (!userreg.mname.value.match(/^[a-zA-Z]+$/)\r\n");
      out.write("\t\t\t&&userreg.mname.value != \"\") {\r\n");
      out.write("\t\t\t\tuserreg.mname.value = \"\";\r\n");
      out.write("\t\t\t\tuserreg.mname.focus();\r\n");
      out.write("\t\t\talert(\"Please Enter only alphabet in text\");\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\r\n");
      out.write("\tif (!userreg.lname.value.match(/^[a-zA-Z]+$/) \r\n");
      out.write("\t\t\t&&userreg.lname.value != \"\") {\r\n");
      out.write("\t\tuserreg.lname.value = \"\";\r\n");
      out.write("\t\tuserreg.lname.focus();\r\n");
      out.write("\talert(\"Please Enter only alphabets in text\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t\r\n");
      out.write("\tif (!userreg.address.value.match(/^[a-zA-Z]+$/) \r\n");
      out.write("\t\t\t&&userreg.address.value != \"\") {\r\n");
      out.write("\t\tuserreg.address.value = \"\";\r\n");
      out.write("\t\tuserreg.address.focus();\r\n");
      out.write("\talert(\"Please Enter only alphabets in text\");\r\n");
      out.write("\t        }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validEmail() {\r\n");
      out.write("\tvar mail=document.userreg.email.value;\r\n");
      out.write("\tif(mail== \"\"){\r\n");
      out.write("alert(\"Enter mailid\");\r\n");
      out.write("document.userreg.email.focus();\r\n");
      out.write("returnfalse;\r\n");
      out.write("    }\r\n");
      out.write("if (/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/.test(mail))  \r\n");
      out.write("    {  \r\n");
      out.write("}else{\r\n");
      out.write("\talert(\"Enter Valid mailid\");\r\n");
      out.write("\tdocument.userreg.email.focus();\r\n");
      out.write("returnfalse;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Validate()\r\n");
      out.write("{ \r\n");
      out.write("var y = document.userreg.mobile.value;\r\n");
      out.write("\r\n");
      out.write("if(isNaN(y)||y.indexOf(\" \")!=-1)\r\n");
      out.write("   {\r\n");
      out.write("\r\n");
      out.write("userreg.mobile.value=\"\";\r\n");
      out.write("userreg.mobile.focus();\r\n");
      out.write("alert(\"Enter Valid Mobile no\");\r\n");
      out.write("returnfalse;\r\n");
      out.write("   }\r\n");
      out.write("if (userreg.mobile.value.length!=10)\r\n");
      out.write("   {\r\n");
      out.write("alert(\"Enter 10 digits No.\");\r\n");
      out.write("returnfalse;\r\n");
      out.write("   } \r\n");
      out.write("\r\n");
      out.write("if (!y.match(/^[0-9]+$/) \r\n");
      out.write("&&y != \"\") {\r\n");
      out.write("y = \"\";\r\n");
      out.write("userreg.mobile.focus();\r\n");
      out.write("alert(\"Please Enter only Digits in text\");\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_header\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\"><font color=\"white\">Intrusion\r\n");
      out.write("\t\t\t\t\t\t\tDetection System</font></a>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END of header -->\r\n");
      out.write("\t\t<div id=\"tooplate_main_wrapper\">\r\n");
      out.write("\t\t\t<span class=\"tmw_frame tmw_framet\"></span><span\r\n");
      out.write("\t\t\t\tclass=\"tmw_frame tmw_frameb\"></span>\r\n");
      out.write("\t\t\t<div id=\"tooplate_menu\" class=\"ddsmoothmenu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\" class=\"selected\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"AdminLogin.jsp\">Admin</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\">User</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register.jsp\">Registration</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<br style=\"clear: left\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end of tooplate_menu -->\r\n");
      out.write("\t\t\t<!-- END of slider -->\r\n");
      out.write("\t\t\t<div id=\"tooplate_main\">\r\n");
      out.write("\t\t\t\t<div id=\"home_about\">\r\n");
      out.write("\t\t\t\t\t<h1>Intrusion Detection System</h1>\r\n");
      out.write("\t\t\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t <img src=\"images/people.png\" width=\"60\" height=\"50\">&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t <td><span style=\"font-size:22px\">Registration</span></td>\r\n");
      out.write("\t\t\t\t </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          <form action=\"reg\" method=\"post\" name=\"userreg\" onsubmit=\"return Regvalidation()\">\r\n");
      out.write("            <center><table>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><strong>First Name</strong></td><td><input type=\"text\" name=\"fname\" onblur=\"AllowAlphabet()\" required id=\"fname\"></input>&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("            <td><strong>Middle Name</strong></td><td><input type=\"text\" name=\"mname\" onblur=\"AllowAlphabet()\" required id= \"mname\"></input>&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("            <td><strong>Last Name</strong></td><td><input type=\"text\" name=\"lname\" id= \"lname\" onblur=\"AllowAlphabet()\" required></input>&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><strong>Date of Birth</strong></td><td><input type=\"text\" name=\"dob\" id=\"popupDatepicker\" required></input></td>\r\n");
      out.write("           \r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><strong>Gender</strong></td><td>&nbsp;Male&nbsp;<input type=\"radio\" name=\"gender\" required id=\"gender\" value=\"male\"></input> &nbsp;Female&nbsp;<input type=\"radio\" name=\"gender\" id=\"gender\" value=\"female\"></input></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><strong>Address</strong></td><td><input type=\"text\" name=\"address\" onblur=\"AllowAlphabet()\" required id=\"address\" maxlength=\"15\"></input></td>\r\n");
      out.write("            <td><strong>City</strong></td><td><input type=\"text\" name=\"city\" required maxlength=\"10\"></input></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><strong>Email Id</strong></td><td><input type=\"text\"  name=\"email\" required id=\"email\" onblur=\"validEmail()\"></input></td>\r\n");
      out.write("            <td><strong>Mobile no</strong></td><td><input type=\"text\" name=\"mobile\" id=\"txtMB\" pattern=\"[7|8|9][0-9]{9}\" maxlength=\"10\" onblur=\"Validate()\" title=\"Phone number Start with 7 or 8 or 9\" required \"></input></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            <tr></tr>\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><strong>UserName</strong></td><td><input type=\"text\" maxlength=\"8\" name=\"username\" id=\"username\" maxlength=\"10\"required></input>&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("            <td><strong>Password</strong></td><td><input type=\"password\" maxlength=\"8\" name=\"password\" id=\"passwords\" required maxlength=\"10\"\"></input></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("           <!-- <tr>\r\n");
      out.write("           <td><strong>File Upload: Select a file to upload:</strong></td><td><input type=\"file\" name=\"file\" size=\"50\" />\r\n");
      out.write("<td><input type=\"submit\" value=\"Upload File\" /></td>\r\n");
      out.write("            \r\n");
      out.write("            </tr> -->\r\n");
      out.write("            <!--  <tr><td></td></tr>-->\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td><input type=\"submit\" style=\"font-size:large; 70px; height: 38px; width:71px;\"></input></td>\r\n");
      out.write("            \r\n");
      out.write("            <td> &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp;\r\n");
      out.write("            <a href=\"register.jsp\"><img src=\"images/reset.png\" width=\"57\" height=\"43\" title=\"Reset\"></img></a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            </table></center>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- END of main wrapper -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END of tooplate_wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_footer_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_footer\">\r\n");
      out.write("\t\t\t<marquee>Intrusion Detection System</marquee>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t<!-- END of tooplate_footer -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END of tooplate_footer_wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tooplate_copyright_wrapper\">\r\n");
      out.write("\t\t<div id=\"tooplate_copyright\">\r\n");
      out.write("\t\t\tCopyright Â© 2048 Your Company Name | Design: <a\r\n");
      out.write("\t\t\t\thref=\"http://www.tooplate.com\">Tooplate</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/scroll-startstop.events.jquery.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar $elem = $('#content');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#nav_up').fadeIn('slow');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(window).bind('scrollstart', function(){\r\n");
      out.write("\t\t\t$('#nav_up,#nav_down').stop().animate({'opacity':'0.2'});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(window).bind('scrollstop', function(){\r\n");
      out.write("\t\t\t$('#nav_up,#nav_down').stop().animate({'opacity':'1'});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#nav_up').click(\r\n");
      out.write("\t\t\tfunction (e) {\r\n");
      out.write("\t\t\t\t$('html, body').animate({scrollTop: '0px'}, 800);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
